### ISSUE TITLE
Error in procfile

### ISSUE THREAD

**Issue by jack4279** [Aritzherrero4/AffiliateTelegramBot#1]
web is not working while doing dyno on

web: python bot.py whats solution

**Comment by Aritzherrero4** [comment]
There is no web interface. It's a telegram bot. It runs as "web" in Heroku but you must use telegram to use the bot as it is mentioned in the readme of the repository.

**Comment by jack4279** [comment]
> There is no web interface. It's a telegram bot. It runs as "web" in Heroku but you must use telegram to use the bot as it is mentioned in the readme of the repository.

But bro as i know we have to on dyno in heroku and there no such interface comes to on my dyno
