### ISSUE TITLE
affiliate_tag

### ISSUE THREAD

**Issue by deepakksharma00079** [Aritzherrero4/AffiliateTelegramBot#4]
Sir I got store id from amazon affiliate website.
You wrote here to put affiliate_tag. What is that sir and how to get it please tell me.
Thanks

**Comment by Aritzherrero4** [comment]
The affiliate-tag is the ID that will identify a link as yours.
It will be something like this: xxxxxx-yy a number of letters and numbers, followed by 2 numbers (-yy) that identify your region.

If you manually generate an affiliate link for a product, you can copy it from there. 

On the Amazon affiliate control panel, you can find it, too. It will appear as Tracking ID or something like that. Search the web if you need more information on the topic.
