### ISSUE TITLE
Short url

### ISSUE THREAD

**Issue by deepakksharma00079** [Aritzherrero4/AffiliateTelegramBot#5]
bro please tell code to make shorten url of amazon like amzn.to or anything

**Comment by Aritzherrero4** [comment]
Same answer given to issue #2. The bot doesn't have it, and I don't feel the need to add external URL shorteners. For amzn.to URLs, you need access to the API and for that you need to meet some requirements, so not everyone can use to it. 

If you really want or need it, you can fork this repo and try to implement it yourself. And then, make a pull request if you feel like it.
