### ISSUE TITLE
Can you please add massage relay on channel and text copying from the 

### ISSUE THREAD

**Issue by Sandybose1** [Aritzherrero4/AffiliateTelegramBot#7]
Hi, I deploy this code but found a drawback it doesn't relay converted amazon link to channel, it just convert the link and reply to it through the bot . Please add a code to relay the replied converted link to a channel. 

Also Now, this code delete the entire message and convert only the link and reply it but can you add a feature like deployed original message with the link both are answered only just changing the link not the message.

**Comment by Aritzherrero4** [comment]
Hello,
I'm not interested on those additions as the project works for my use case. You can try to implement it yourself and do a PR afterwards. If everything works correctly, I might merge it.

**Comment by Aritzherrero4** [comment]
Hello,
I'm not interested on those additions as the project works for my use case. You can try to implement it yourself and do a PR afterwards. If everything works correctly, I might merge it.
